import time
from typing import List, Optional
from fastapi import APIRouter, HTTPException, Query, status
from app.schemas.detection import (
    PredictionResponse,
    ScanSummary,
    StatsResponse,
    ReportResponse,
)
from app.storage.repository import scan_repository

from fastapi.responses import HTMLResponse

router = APIRouter(tags=["Scans & Reports"])


@router.get("/scans", response_model=List[PredictionResponse])
def list_scans(
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
) -> List[PredictionResponse]:
    """Retrieves all past analyzed sonar scans sorted newest first."""
    return scan_repository.list_all(limit=limit, offset=offset)


@router.get("/scans/{scan_id}", response_model=PredictionResponse)
def get_scan(scan_id: str) -> PredictionResponse:
    """Retrieves detailed detection result for a specific scan ID."""
    scan = scan_repository.get(scan_id)
    if not scan:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scan with ID '{scan_id}' not found.",
        )
    return scan


@router.delete("/scans/{scan_id}", status_code=status.HTTP_200_OK)
def delete_scan(scan_id: str):
    """Deletes a scan from the repository."""
    deleted = scan_repository.delete(scan_id)
    if not deleted:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scan with ID '{scan_id}' not found.",
        )
    return {"status": "success", "message": f"Scan '{scan_id}' deleted."}


@router.get("/stats", response_model=StatsResponse)
def get_statistics() -> StatsResponse:
    """Computes real aggregate metrics across all processed sonar scans."""
    return scan_repository.get_stats()


@router.get("/scans/{scan_id}/report", response_model=ReportResponse)
def generate_scan_report(scan_id: str) -> ReportResponse:
    """
    Generates a structured acoustic inspection report for a given scan.
    Clearly reflects actual model classes.
    """
    scan = scan_repository.get(scan_id)
    if not scan:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scan with ID '{scan_id}' not found.",
        )

    total = scan.total_detections

    if total == 0:
        analyst_summary = (
            f"Sonar scan '{scan.filename}' was evaluated with {scan.model_name} ({scan.model_version}) "
            f"at confidence cutoff {scan.confidence_threshold:.2f}. No model detections "
            f"exceeded the threshold. Highest model confidence detected: {scan.highest_confidence * 100:.1f}%."
        )
    else:
        if scan.model_version == "v2":
            analyst_summary = (
                f"Ministry of Earth Sciences (MoES) SIH AI Inspection identified {total} target(s) in '{scan.filename}'. "
                f"Breakdown: {scan.ghost_net_count} Ghost Net/ALDFG contact(s), {scan.debris_count} Anthropogenic Debris, "
                f"{scan.pipeline_count} Pipeline Hazard(s), and {scan.anomaly_count} Seafloor Anomaly contact(s). "
                f"Peak target confidence: {scan.highest_confidence * 100:.1f}%. "
                f"Inference latency: {scan.inference_ms:.1f} ms."
            )
        else:
            analyst_summary = (
                f"YOLOv8 acoustic inspection identified {total} target(s) in '{scan.filename}'. "
                f"Breakdown: {scan.milco_count} MILCO (Mine Contact) and {scan.nombo_count} NOMBO (Obstacle). "
                f"Peak target confidence: {scan.highest_confidence * 100:.1f}%. "
                f"Inference latency: {scan.inference_ms:.1f} ms."
            )

    disclaimer = (
        "CONFIDENTIALITY & SCIENTIFIC NOTICE: Generated by SIH AI-Powered Automated Underwater Marine Debris "
        "and Anomaly Detection System (MoES Track). Ground-truth ROV/diver verification recommended."
    )

    return ReportResponse(
        scan=scan,
        generated_at=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        analyst_summary=analyst_summary,
        disclaimer=disclaimer,
        metrics={
            "total_detections": total,
            "ghost_net_count": scan.ghost_net_count,
            "debris_count": scan.debris_count,
            "pipeline_count": scan.pipeline_count,
            "anomaly_count": scan.anomaly_count,
            "highest_confidence": scan.highest_confidence,
            "inference_ms": scan.inference_ms,
            "has_geolocation": scan.location.latitude is not None
            and scan.location.longitude is not None,
        },
    )


@router.get("/scans/{scan_id}/report/html", response_class=HTMLResponse)
def get_printable_html_report(scan_id: str):
    """
    Generates a publication-ready, printable HTML/PDF intelligence dossier for a scan.
    Designed for print (Ctrl+P / Save to PDF) and executive presentation.
    """
    scan = scan_repository.get(scan_id)
    if not scan:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scan with ID '{scan_id}' not found.",
        )

    report_data = generate_scan_report(scan_id)

    detections_rows = ""
    for idx, d in enumerate(scan.detections, 1):
        x1, y1, x2, y2 = d.bbox.x1, d.bbox.y1, d.bbox.x2, d.bbox.y2
        tier = d.confidence_tier or ("HIGH" if d.confidence >= 0.70 else "MEDIUM")
        detections_rows += f"""
        <tr>
            <td><strong>#0{idx}</strong></td>
            <td><code>{d.type}</code></td>
            <td><strong style="color: #0d9488;">{d.confidence * 100:.1f}%</strong></td>
            <td><span class="badge {tier.lower()}">{tier}</span></td>
            <td>({x1}, {y1}) &rarr; ({x2}, {y2})</td>
        </tr>
        """

    if not detections_rows:
        detections_rows = "<tr><td colspan='5' style='text-align: center; color: #64748b;'>No targets detected above confidence threshold.</td></tr>"

    lat_str = f"{scan.location.latitude:.4f}&deg;N" if scan.location.latitude else "N/A"
    lon_str = f"{scan.location.longitude:.4f}&deg;E" if scan.location.longitude else "N/A"

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SONARX Intelligence Dossier - {scan.scan_id}</title>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 0; padding: 30px; background: #0f172a; color: #f8fafc; line-height: 1.5; }}
        .card {{ background: #1e293b; border: 1px solid #334155; border-radius: 12px; padding: 24px; margin-bottom: 20px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.3); }}
        .header {{ display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #0d9488; padding-bottom: 16px; margin-bottom: 20px; }}
        .title {{ font-size: 20px; font-weight: 800; color: #2dd4bf; letter-spacing: 1px; }}
        .subtitle {{ font-size: 11px; color: #94a3b8; text-transform: uppercase; margin-top: 4px; }}
        .grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 20px; }}
        .metric-box {{ background: #0f172a; border: 1px solid #334155; padding: 12px; border-radius: 8px; font-family: monospace; }}
        .metric-label {{ font-size: 10px; color: #94a3b8; text-transform: uppercase; }}
        .metric-val {{ font-size: 18px; font-weight: bold; color: #2dd4bf; margin-top: 4px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 12px; }}
        th {{ background: #0f172a; text-align: left; padding: 10px; border-bottom: 2px solid #334155; color: #cbd5e1; text-transform: uppercase; font-size: 10px; }}
        td {{ padding: 10px; border-bottom: 1px solid #334155; }}
        .badge {{ padding: 2px 8px; border-radius: 4px; font-weight: bold; font-size: 10px; }}
        .badge.high {{ background: rgba(45,212,191,0.2); color: #2dd4bf; border: 1px solid #2dd4bf; }}
        .badge.medium {{ background: rgba(251,146,60,0.2); color: #fb923c; border: 1px solid #fb923c; }}
        .footer {{ font-size: 10px; color: #64748b; margin-top: 30px; text-align: center; border-top: 1px solid #334155; padding-top: 16px; }}
        .no-print { display: flex; }
        @media print {
            body { background: white; color: black; padding: 0; }
            .card { background: white; border: 1px solid #ccc; color: black; box-shadow: none; }
            .metric-box { background: #f8fafc; border: 1px solid #ccc; color: black; }
            .metric-val { color: #0f766e; }
            th { background: #f1f5f9; color: black; }
            td { border-bottom: 1px solid #ddd; }
            .no-print { display: none !important; }
        }
    </style>
</head>
<body>
    <div style="max-width: 900px; margin: 0 auto 16px auto; display: flex; justify-content: flex-end; gap: 10px;" class="no-print">
        <button onclick="window.print()" style="background: #0284c7; color: white; border: none; padding: 8px 18px; border-radius: 6px; font-weight: bold; cursor: pointer; font-size: 13px;">🖨️ Print / Save as PDF</button>
        <button onclick="window.close()" style="background: #334155; color: white; border: none; padding: 8px 14px; border-radius: 6px; font-weight: bold; cursor: pointer; font-size: 13px;">Close</button>
    </div>
    <div class="card" style="max-width: 900px; margin: 0 auto;">
        <div class="header">
            <div>
                <div class="title">SONARX // SUBSEA INTELLIGENCE DOSSIER</div>
                <div class="subtitle">Ministry of Earth Sciences (MoES) · NIOT PS 26057</div>
            </div>
            <div style="text-align: right; font-family: monospace; font-size: 11px; color: #94a3b8;">
                <div>DOSSIER ID: <strong>{scan.scan_id}</strong></div>
                <div>DATE: {report_data.generated_at}</div>
            </div>
        </div>

        <div class="grid">
            <div class="metric-box">
                <div class="metric-label">Target File</div>
                <div class="metric-val" style="font-size: 13px; color: #f8fafc;">{scan.filename}</div>
            </div>
            <div class="metric-box">
                <div class="metric-label">Detections Found</div>
                <div class="metric-val">{scan.total_detections}</div>
            </div>
            <div class="metric-box">
                <div class="metric-label">Peak Confidence</div>
                <div class="metric-val">{scan.highest_confidence * 100:.1f}%</div>
            </div>
            <div class="metric-box">
                <div class="metric-label">Geospatial Fix</div>
                <div class="metric-val" style="font-size: 12px;">{lat_str}, {lon_str}</div>
            </div>
        </div>

        <div style="background: #0f172a; padding: 14px; border-radius: 8px; border-left: 4px solid #2dd4bf; font-size: 12px; margin-bottom: 20px;">
            <strong style="color: #2dd4bf; text-transform: uppercase; font-size: 10px; display: block; margin-bottom: 4px;">Executive Analyst Summary</strong>
            {report_data.analyst_summary}
        </div>

        <div style="font-size: 12px; font-weight: bold; color: #f8fafc; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px;">
            Target Contact Inventory
        </div>
        <table>
            <thead>
                <tr>
                    <th>Contact ID</th>
                    <th>Target Class</th>
                    <th>Confidence</th>
                    <th>Tier</th>
                    <th>Bounding Coordinates</th>
                </tr>
            </thead>
            <tbody>
                {detections_rows}
            </tbody>
        </table>

        <div class="footer">
            {report_data.disclaimer}<br>
            Powered by SONARX YOLOv8s ONNX Engine · Evaluated on 5,205 Multi-Source Side-Scan Sonar Tiles (74.1% mAP50)
        </div>
    </div>
    <script>
        window.addEventListener('load', function() {
            setTimeout(function() {
                window.print();
            }, 300);
        });
    </script>
</body>
</html>"""

    return HTMLResponse(content=html_content)
