import time
from typing import List, Optional
from fastapi import APIRouter, HTTPException, Query, status
from app.schemas.detection import (
    PredictionResponse,
    ScanSummary,
    StatsResponse,
    ReportResponse,
)
from app.storage.repository import scan_repository

router = APIRouter(tags=["Scans & Reports"])


@router.get("/scans", response_model=List[PredictionResponse])
def list_scans(
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
) -> List[PredictionResponse]:
    """Retrieves all past analyzed sonar scans sorted newest first."""
    return scan_repository.list_all(limit=limit, offset=offset)


@router.get("/scans/{scan_id}", response_model=PredictionResponse)
def get_scan(scan_id: str) -> PredictionResponse:
    """Retrieves detailed detection result for a specific scan ID."""
    scan = scan_repository.get(scan_id)
    if not scan:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scan with ID '{scan_id}' not found.",
        )
    return scan


@router.delete("/scans/{scan_id}", status_code=status.HTTP_200_OK)
def delete_scan(scan_id: str):
    """Deletes a scan from the repository."""
    deleted = scan_repository.delete(scan_id)
    if not deleted:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scan with ID '{scan_id}' not found.",
        )
    return {"status": "success", "message": f"Scan '{scan_id}' deleted."}


@router.get("/stats", response_model=StatsResponse)
def get_statistics() -> StatsResponse:
    """Computes real aggregate metrics across all processed sonar scans."""
    return scan_repository.get_stats()


@router.get("/scans/{scan_id}/report", response_model=ReportResponse)
def generate_scan_report(scan_id: str) -> ReportResponse:
    """
    Generates a structured acoustic inspection report for a given scan.
    Clearly reflects actual model classes (MILCO / NOMBO).
    """
    scan = scan_repository.get(scan_id)
    if not scan:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scan with ID '{scan_id}' not found.",
        )

    total = scan.total_detections
    milco_cnt = scan.milco_count
    nombo_cnt = scan.nombo_count

    if total == 0:
        analyst_summary = (
            f"Sonar scan '{scan.filename}' was evaluated with {scan.model_name} "
            f"at confidence cutoff {scan.confidence_threshold:.2f}. No model detections "
            f"exceeded the threshold. Highest model confidence detected: {scan.highest_confidence * 100:.1f}%."
        )
    else:
        analyst_summary = (
            f"YOLOv8 acoustic inspection identified {total} target(s) in '{scan.filename}'. "
            f"Classification breakdown: {milco_cnt} MILCO (Mine-Like Contact) target(s) and "
            f"{nombo_cnt} NOMBO (Non-Mine Bottom Obstacle) target(s). "
            f"Highest target confidence: {scan.highest_confidence * 100:.1f}%. "
            f"Inference latency: {scan.inference_ms:.1f} ms."
        )

    disclaimer = (
        "CONFIDENTIALITY & SCIENTIFIC NOTICE: Detections are generated by the YOLOv8n MILCO/NOMBO "
        "sonar baseline model. Marine Sonar V2 model is under active development to incorporate pipeline, "
        "derelict fishing gear, and shipwreck classes."
    )

    return ReportResponse(
        scan=scan,
        generated_at=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        analyst_summary=analyst_summary,
        disclaimer=disclaimer,
        metrics={
            "total_detections": total,
            "milco_count": milco_cnt,
            "nombo_count": nombo_cnt,
            "highest_confidence": scan.highest_confidence,
            "inference_ms": scan.inference_ms,
            "has_geolocation": scan.location.latitude is not None
            and scan.location.longitude is not None,
        },
    )
