import time
from typing import List, Optional
from fastapi import APIRouter, HTTPException, Query, status
from app.schemas.detection import (
    PredictionResponse,
    ScanSummary,
    StatsResponse,
    ReportResponse,
)
from app.storage.repository import scan_repository

router = APIRouter(tags=["Scans & Reports"])


@router.get("/scans", response_model=List[PredictionResponse])
def list_scans(
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
) -> List[PredictionResponse]:
    """Retrieves all past analyzed sonar scans sorted newest first."""
    return scan_repository.list_all(limit=limit, offset=offset)


@router.get("/scans/{scan_id}", response_model=PredictionResponse)
def get_scan(scan_id: str) -> PredictionResponse:
    """Retrieves detailed detection result for a specific scan ID."""
    scan = scan_repository.get(scan_id)
    if not scan:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scan with ID '{scan_id}' not found.",
        )
    return scan


@router.delete("/scans/{scan_id}", status_code=status.HTTP_200_OK)
def delete_scan(scan_id: str):
    """Deletes a scan from the repository."""
    deleted = scan_repository.delete(scan_id)
    if not deleted:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scan with ID '{scan_id}' not found.",
        )
    return {"status": "success", "message": f"Scan '{scan_id}' deleted."}


@router.get("/stats", response_model=StatsResponse)
def get_statistics() -> StatsResponse:
    """Computes real aggregate metrics across all processed sonar scans."""
    return scan_repository.get_stats()


@router.get("/scans/{scan_id}/report", response_model=ReportResponse)
def generate_scan_report(scan_id: str) -> ReportResponse:
    """
    Generates a structured acoustic inspection report for a given scan.
    Clearly reflects actual model classes.
    """
    scan = scan_repository.get(scan_id)
    if not scan:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scan with ID '{scan_id}' not found.",
        )

    total = scan.total_detections

    if total == 0:
        analyst_summary = (
            f"Sonar scan '{scan.filename}' was evaluated with {scan.model_name} ({scan.model_version}) "
            f"at confidence cutoff {scan.confidence_threshold:.2f}. No model detections "
            f"exceeded the threshold. Highest model confidence detected: {scan.highest_confidence * 100:.1f}%."
        )
    else:
        if scan.model_version == "v2":
            analyst_summary = (
                f"Ministry of Earth Sciences (MoES) SIH AI Inspection identified {total} target(s) in '{scan.filename}'. "
                f"Breakdown: {scan.ghost_net_count} Ghost Net/ALDFG contact(s), {scan.debris_count} Anthropogenic Debris, "
                f"{scan.pipeline_count} Pipeline Hazard(s), and {scan.anomaly_count} Seafloor Anomaly contact(s). "
                f"Peak target confidence: {scan.highest_confidence * 100:.1f}%. "
                f"Inference latency: {scan.inference_ms:.1f} ms."
            )
        else:
            analyst_summary = (
                f"YOLOv8 acoustic inspection identified {total} target(s) in '{scan.filename}'. "
                f"Breakdown: {scan.milco_count} MILCO (Mine Contact) and {scan.nombo_count} NOMBO (Obstacle). "
                f"Peak target confidence: {scan.highest_confidence * 100:.1f}%. "
                f"Inference latency: {scan.inference_ms:.1f} ms."
            )

    disclaimer = (
        "CONFIDENTIALITY & SCIENTIFIC NOTICE: Generated by SIH AI-Powered Automated Underwater Marine Debris "
        "and Anomaly Detection System (MoES Track). Ground-truth ROV/diver verification recommended."
    )

    return ReportResponse(
        scan=scan,
        generated_at=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        analyst_summary=analyst_summary,
        disclaimer=disclaimer,
        metrics={
            "total_detections": total,
            "ghost_net_count": scan.ghost_net_count,
            "debris_count": scan.debris_count,
            "pipeline_count": scan.pipeline_count,
            "anomaly_count": scan.anomaly_count,
            "highest_confidence": scan.highest_confidence,
            "inference_ms": scan.inference_ms,
            "has_geolocation": scan.location.latitude is not None
            and scan.location.longitude is not None,
        },
    )
